AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lilu

  Sample SAM Template for lilu

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  LiluFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lilu/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        Lilu:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LiluApi:
    Description: "API Gateway endpoint URL for Prod stage for Lilu function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  LiluFunction:
    Description: "Lilu Lambda Function ARN"
    Value: !GetAtt LiluFunction.Arn
  LiluFunctionIamRole:
    Description: "Implicit IAM Role created for Lilu function"
    Value: !GetAtt LiluFunctionRole.Arn
